/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Scene.node;

import gdx.game.Scene.analysis.*;

@SuppressWarnings("nls")
public final class APostSubIncrement extends PIncrement
{
    private TIdent _ident_;
    private TMinusInc _minusInc_;

    public APostSubIncrement()
    {
        // Constructor
    }

    public APostSubIncrement(
        @SuppressWarnings("hiding") TIdent _ident_,
        @SuppressWarnings("hiding") TMinusInc _minusInc_)
    {
        // Constructor
        setIdent(_ident_);

        setMinusInc(_minusInc_);

    }

    @Override
    public Object clone()
    {
        return new APostSubIncrement(
            cloneNode(this._ident_),
            cloneNode(this._minusInc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostSubIncrement(this);
    }

    public TIdent getIdent()
    {
        return this._ident_;
    }

    public void setIdent(TIdent node)
    {
        if(this._ident_ != null)
        {
            this._ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ident_ = node;
    }

    public TMinusInc getMinusInc()
    {
        return this._minusInc_;
    }

    public void setMinusInc(TMinusInc node)
    {
        if(this._minusInc_ != null)
        {
            this._minusInc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusInc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ident_)
            + toString(this._minusInc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ident_ == child)
        {
            this._ident_ = null;
            return;
        }

        if(this._minusInc_ == child)
        {
            this._minusInc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        if(this._minusInc_ == oldChild)
        {
            setMinusInc((TMinusInc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
