/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Scene.node;

import java.util.*;
import gdx.game.Scene.analysis.*;

@SuppressWarnings("nls")
public final class AThenPart extends PThenPart
{
    private TThen _then_;
    private final LinkedList<PInst> _insts_ = new LinkedList<PInst>();

    public AThenPart()
    {
        // Constructor
    }

    public AThenPart(
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") List<?> _insts_)
    {
        // Constructor
        setThen(_then_);

        setInsts(_insts_);

    }

    @Override
    public Object clone()
    {
        return new AThenPart(
            cloneNode(this._then_),
            cloneList(this._insts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThenPart(this);
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public LinkedList<PInst> getInsts()
    {
        return this._insts_;
    }

    public void setInsts(List<?> list)
    {
        for(PInst e : this._insts_)
        {
            e.parent(null);
        }
        this._insts_.clear();

        for(Object obj_e : list)
        {
            PInst e = (PInst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._insts_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._then_)
            + toString(this._insts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._insts_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        for(ListIterator<PInst> i = this._insts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
