/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Scene.node;

import gdx.game.Scene.analysis.*;

@SuppressWarnings("nls")
public final class TFrameAdvance extends Token
{
    public TFrameAdvance()
    {
        super.setText("frameAdvance");
    }

    public TFrameAdvance(int line, int pos)
    {
        super.setText("frameAdvance");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFrameAdvance(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFrameAdvance(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFrameAdvance text.");
    }
}
