/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Interp.node;

import gdx.game.Interp.analysis.*;

@SuppressWarnings("nls")
public final class AAssignerInst extends PInst
{
    private PAssigner _assigner_;
    private TSc _sc_;

    public AAssignerInst()
    {
        // Constructor
    }

    public AAssignerInst(
        @SuppressWarnings("hiding") PAssigner _assigner_,
        @SuppressWarnings("hiding") TSc _sc_)
    {
        // Constructor
        setAssigner(_assigner_);

        setSc(_sc_);

    }

    @Override
    public Object clone()
    {
        return new AAssignerInst(
            cloneNode(this._assigner_),
            cloneNode(this._sc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignerInst(this);
    }

    public PAssigner getAssigner()
    {
        return this._assigner_;
    }

    public void setAssigner(PAssigner node)
    {
        if(this._assigner_ != null)
        {
            this._assigner_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assigner_ = node;
    }

    public TSc getSc()
    {
        return this._sc_;
    }

    public void setSc(TSc node)
    {
        if(this._sc_ != null)
        {
            this._sc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assigner_)
            + toString(this._sc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assigner_ == child)
        {
            this._assigner_ = null;
            return;
        }

        if(this._sc_ == child)
        {
            this._sc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assigner_ == oldChild)
        {
            setAssigner((PAssigner) newChild);
            return;
        }

        if(this._sc_ == oldChild)
        {
            setSc((TSc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
