/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Interp.node;

import gdx.game.Interp.analysis.*;

@SuppressWarnings("nls")
public final class APreAddIncrement extends PIncrement
{
    private TPlusInc _plusInc_;
    private TIdent _ident_;

    public APreAddIncrement()
    {
        // Constructor
    }

    public APreAddIncrement(
        @SuppressWarnings("hiding") TPlusInc _plusInc_,
        @SuppressWarnings("hiding") TIdent _ident_)
    {
        // Constructor
        setPlusInc(_plusInc_);

        setIdent(_ident_);

    }

    @Override
    public Object clone()
    {
        return new APreAddIncrement(
            cloneNode(this._plusInc_),
            cloneNode(this._ident_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreAddIncrement(this);
    }

    public TPlusInc getPlusInc()
    {
        return this._plusInc_;
    }

    public void setPlusInc(TPlusInc node)
    {
        if(this._plusInc_ != null)
        {
            this._plusInc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusInc_ = node;
    }

    public TIdent getIdent()
    {
        return this._ident_;
    }

    public void setIdent(TIdent node)
    {
        if(this._ident_ != null)
        {
            this._ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ident_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusInc_)
            + toString(this._ident_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusInc_ == child)
        {
            this._plusInc_ = null;
            return;
        }

        if(this._ident_ == child)
        {
            this._ident_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusInc_ == oldChild)
        {
            setPlusInc((TPlusInc) newChild);
            return;
        }

        if(this._ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
