/* This file was generated by SableCC (http://www.sablecc.org/). */

package gdx.game.Interp.node;

import gdx.game.Interp.analysis.*;

@SuppressWarnings("nls")
public final class APreSubIncrement extends PIncrement
{
    private TMinusInc _minusInc_;
    private TIdent _ident_;

    public APreSubIncrement()
    {
        // Constructor
    }

    public APreSubIncrement(
        @SuppressWarnings("hiding") TMinusInc _minusInc_,
        @SuppressWarnings("hiding") TIdent _ident_)
    {
        // Constructor
        setMinusInc(_minusInc_);

        setIdent(_ident_);

    }

    @Override
    public Object clone()
    {
        return new APreSubIncrement(
            cloneNode(this._minusInc_),
            cloneNode(this._ident_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreSubIncrement(this);
    }

    public TMinusInc getMinusInc()
    {
        return this._minusInc_;
    }

    public void setMinusInc(TMinusInc node)
    {
        if(this._minusInc_ != null)
        {
            this._minusInc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusInc_ = node;
    }

    public TIdent getIdent()
    {
        return this._ident_;
    }

    public void setIdent(TIdent node)
    {
        if(this._ident_ != null)
        {
            this._ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ident_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusInc_)
            + toString(this._ident_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusInc_ == child)
        {
            this._minusInc_ = null;
            return;
        }

        if(this._ident_ == child)
        {
            this._ident_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusInc_ == oldChild)
        {
            setMinusInc((TMinusInc) newChild);
            return;
        }

        if(this._ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
